# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dgcmatrix_row_scale <- function(mat, scale = TRUE, center = TRUE, scale_max = 10) {
    .Call('_scTenifoldNet_dgcmatrix_row_scale', PACKAGE = 'scTenifoldNet', mat, scale, center, scale_max)
}

dgcmatrix_row_scale2 <- function(mat, mu, sigma, scale = TRUE, center = TRUE, scale_max = 10) {
    .Call('_scTenifoldNet_dgcmatrix_row_scale2', PACKAGE = 'scTenifoldNet', mat, mu, sigma, scale, center, scale_max)
}

dgcmatrix_rowsums <- function(mat) {
    .Call('_scTenifoldNet_dgcmatrix_rowsums', PACKAGE = 'scTenifoldNet', mat)
}

dgcmatrix_rowmeans <- function(mat) {
    .Call('_scTenifoldNet_dgcmatrix_rowmeans', PACKAGE = 'scTenifoldNet', mat)
}

dgcmatrix_rowvars_know_means <- function(mat, mu) {
    .Call('_scTenifoldNet_dgcmatrix_rowvars_know_means', PACKAGE = 'scTenifoldNet', mat, mu)
}

dgcmatrix_rowvars <- function(mat) {
    .Call('_scTenifoldNet_dgcmatrix_rowvars', PACKAGE = 'scTenifoldNet', mat)
}

dgcmatrix_rowmeans_expm1 <- function(mat) {
    .Call('_scTenifoldNet_dgcmatrix_rowmeans_expm1', PACKAGE = 'scTenifoldNet', mat)
}

matrix_rowmeans_expm1 <- function(mat) {
    .Call('_scTenifoldNet_matrix_rowmeans_expm1', PACKAGE = 'scTenifoldNet', mat)
}

dgcmatrix_rowvars_expm1_know_means <- function(mat, mu) {
    .Call('_scTenifoldNet_dgcmatrix_rowvars_expm1_know_means', PACKAGE = 'scTenifoldNet', mat, mu)
}

dgcmatrix_rowvars_expm1 <- function(mat) {
    .Call('_scTenifoldNet_dgcmatrix_rowvars_expm1', PACKAGE = 'scTenifoldNet', mat)
}

#' @title Core PC Network computation (C++ backend)
#'
#' @description Computes the gene coefficient matrix using principal component
#' regression. For each gene K, regresses it against principal components
#' derived from all other genes via truncated SVD.
#'
#' @param X_std A standardized numeric matrix (samples x genes), centered
#'   and scaled by column.
#' @param nComp Number of principal components to use.
#'
#' @return A numeric matrix (n_genes x (n_genes - 1)) of regression coefficients.
#'
#' @keywords internal
pcNetCoreRcpp <- function(X_std, nComp) {
    .Call('_scTenifoldNet_pcNetCoreRcpp', PACKAGE = 'scTenifoldNet', X_std, nComp)
}

